version: "3"
services:
    main:
        container_name: "teagram"
        build:
            context: .
        volumes:
            - main:/data
        stop_signal: SIGINT
        restart: never
        command: python3.11 -m teagram

volumes:
    main:
